### ISSUE TITLE
Manter Instituições de Solidariedade Social

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#13]

**Comment by fredcido** [comment]
@gilsonterra Observações:
- Crie um placeholder para as descriptions, só para poder ficar melhor a separação dos dados gerais com as descriptions
- Se possível, ainda estou achando estranho esses botões _Add_ dentro das abas, veja se tem como colocá-los melhor posicionados, um botão ocupando uma linha inteira me parece falha de UX.
- Falando em botões, o _Create_ ainda não está bloqueado até o usuário adicionar uma Social Response
- Retire a máscara do postalCode, eles não seguem isso aqui fora
- Eu vou criar uma entidade de Bank para os bancos serem pré-cadastrados, muda na tela para pegar do endpoint
- Faça a combo de InterventionArea como select2 e coloca ela full width
- Nos endereços, deixe Posto Administrativo e Suku readonly até ele seleciona a respectiva combo que carrega seus dados. Mas sempre required
- Na tela de InterventionArea, vai ter que ser dialog, porque ele vai querer a visão em grid de cada SocialResponse embaixo da outra, para comparar os dados. Pode usar esse mesmo form dentro da dialog, mas na visualização rápida precisa ser grid, como no Excel.
- Em todas as telas, quando clickar no botão _Add_ faça a passagem fazer um scroll até o container criada. No General.js tem um scrollTo, se não me engano. General.scrollTo('seletor');
- Na aba de InterventionArea, quando ele clickar em adicionar uma nova SocialResponse, se o container da IA estiver fechado, abra ele e então adicione, se vc adicionar com ele fechado, além do usuário não ver e o scrollTo não funcionar, as select2 ficam com o width todo bichado.

**Comment by fredcido** [comment]
@gilsonterra Por que as labels da sua tela estão todas estranhas e em minúsculo? Coloca um title nelas ai

**Comment by fredcido** [comment]
@gilsonterra o backend está pronto e salvando as primeiras abas, menos a de áreas de intervenção que parece meio falhada. Eu mexi em algumas tags do riot para poder adequar ao padrão, não mexi nessa última porque ela está bem estranha e não tinha certeza se queria colocar a mão antes de você mexer. 
- O campo total não calcula mais
- A listagem de RS na grid está falhada, tem que mostrar o resto das informações
- Se for caso remove o label dos botões da grid mas deixa os dois na mesma linha
- Mais uma vez, suas labels estão estranhas, aplica title nelas.
- Colocas combo como select2

**Comment by gilsonterra** [comment]
@fredcido Testa a tela com amor! S2
