### ISSUE TITLE
Preparar estrutura para mensagens em JS com boostrap e tradução

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#16]

**Comment by fredcido** [comment]
Estruturar uma forma, de preferência aqui genérico que suporte mensagens e traduções em JS. Coloquei um Message.js na pasta de javascripts que costume utilizar para mensagens no padrão do twitter bootstrap. Pode ser melhorado e adaptado.

**Comment by fredcido** [comment]
Terminar de configurar o seguinte bundle: https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md

**Comment by adrianorc** [comment]
Finalizei a configuração do BazingaJsTranslationBundle. Pra isso foi necesário instalar outro bundle (AsseticBundle).

Sempre que existir alterações nas mensagens (inclusão de nova mensagem, traduções, etc), é necessário atualizar as mensagens no Bazinga, com os comandos:

php bin/console bazinga:js-translation:dump ./web/assets/js
php bin/console assetic:dump

Pra traduzir mensagens no JS, utilizar o servço Translator, passando a key da mensagem e o dominio, por ex:

Translator.trans('crud.action.create', {}, 'GeneralMessages')
