### ISSUE TITLE
Manter Programas vs Rúbricas de Despesas

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#20]

**Comment by gilsonterra** [comment]
Ta usando o padrão do symfony. Depois melhorar para caso de muitas expenses

**Comment by fredcido** [comment]
@adrianorc Assume esse pra gente, você já sabe como trabalhar com os forms do Symfony para criar registros dinâmicos. Na hora de registrar programas você já pode vincular Rúbricas de Despesas a ele (Expenses). Pode fazer uma grid com jquery mesmo. 

Traz uma combo com Expenses que o usuário seleciona, clica em add e vai pra grid, validações de Expenses repetidas tanto no JS da grid como na Entity.

Se quiser trazer duas combos para facilitar melhor ainda, uma de Type Expense e outra de Expense. Selecionando Type Expense filtra as Expenses e ele seleciona qual vincular ao programa. Para essas buscas de dados em ajax que podem ser usadas em vários lugares, tipo buscar Expenses por Expense Type, coloca no DataRepositoryController, pra gente poder reproveitar os JSON da vida.
