### ISSUE TITLE
Estruturar gerenciador de midia/arquivos

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#21]
Procurar bundle que aceite você passar qualquer entidade e gerenciadr midias para essa entidade. Se não houver, vamos discutir alguma implementação

**Comment by fredcido** [comment]
Isso será usado nessa tela de ISS 

![image](https://zube.io/files/fredcido/fba18a191cc82a6714675276042e8b2f.png)

Ele vai poder subir quantos arquivos quiser, fazer uma aba como se fosse um gerenciador de arquivos. Verificar a possibilidade de poder usar esse gerenciador com outras entidades. Se for o caso criar um simplificado.

**Comment by gilsonterra** [comment]
@fredcido Esse gerenciador só vai aparecer depois que ele salvar a ISS ou ja vai mandar mesmo não tendo salvo?

**Comment by fredcido** [comment]
@gilsonterra Pode ser.
Eu pensei em criar um serviço genérico que recebesse uma entidade e pudesse persistir e controlar midias dessa entidade. Como exemplo:

``` php
// Salva os arquivos
$service->saveMedia($entity, $files);
// Retorna os arquivos salvos
$service->getMedia($entity);
```

Ele pegaria a entidade, criaria uma pasta com o nome da entidade no web/uploads e para cada entidade pegaria o ID para vincular as mídias. Vamos supor nesse caso de ISS. Ele criaria uma pasta

web/uploads/social-institution/10/[FILES]

Para criar esse slug deve ter algo pronto, não reinvente a roda, use o class name. Você já trabalhou com algo semelhante em outro projeto nosso, mas não precisa de tanta validação. Somente tipo de arquivos válidos.
