### ISSUE TITLE
Criar um serviço para resgate de dados de configuração

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#27]
Vamos criar um serviço para resgatar dados de configuração de forma fácil e simples. Podemos definir constantes ou passar o nome do Repositorio. Penso em criar esse serviço para podermos usar de forma rápida e quem sabe futuramente implementar cache. Algo como:

```
<?php
$configuration = $this->get('mss_configuration');
// Todos os programas
$programs = $configuration->all('Programs');

// Pega o programa com ID 1
$programas = $configuration->get('Programs', 1);
```

**Comment by globtec** [comment]
Podemos utilizar o Repository Pattern de qualquer serviço, acredito que não seja necessário a criação deste serviço.

``` php
// Todos os programas
$programs = $this->getRepository('Programs')->findAll();

// Pega o programa com ID 1
$program =  $this->getRepository('Programs')->find(1);
```
