### ISSUE TITLE
Criar um controller genérico para dados em Ajax

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#28]
Vejo que constantemente precisaremos buscar dados em Ajax, como programas, rúbricas de despesas de acordo com a Área de Intervenção, Postos administrativos de acordo com o municipio. Criar um controller que retorna isso em JSON os Ajaxs da vida, a ROLE mínima para usuários acessarem isso é de USER.

**Comment by gilsonterra** [comment]
Criei o controller porem sem nenhuma action. Quando alguem precisar ja ta pronto so usar ele
