### ISSUE TITLE
Por que estamos utilizando diferentes domains para tradução?

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#34]
Na aplicação tem domain GeneralMessages e AppBundle, por que estamos usando diferentes? Deveríamos manter tudo dentro de um só

**Comment by adrianorc** [comment]
O domain é uma maneira de separar as mensagens por áreas específicas. Por ex, você pode ter um domain para o menu principal, um domain para uma sidebar, um domian para um bundle. O que acha melhor, deixar um domain só para a aplicação toda?
