### ISSUE TITLE
Mostrar resultados inativos em todas as telas

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#40]
Em todas as telas administrativas mostrar também resultados inativos e possibilidade de reativar.

**Comment by fredcido** [comment]
@globtec Fiz um teste, ao desativar usando o menu rápido a direita da tela e a checkbox, ele não recarrega o botão "Inativar" na grid. Se eu clickar nesse botão ele está deletando registro, não vamos deletar nada.

**Comment by globtec** [comment]
@fredcido Esta ação deve permanecer mesmo com a implementação da opção "change status"? ela deve ser ajustada para inativar? e se já estiver inativo a ação deve ser para ativar?

**Comment by fredcido** [comment]
@globtec Com a implementação da combo, pode remover o botão da grid. Mas ele pode reativar sim.
