### ISSUE TITLE
Implementação back-end da API

### ISSUE THREAD

**Issue by globtec** [fredcido/mss-iss#43]

**Comment by fredcido** [comment]
@gilsonterra @globtec Mudem as rotas no DataRepositoryController para seguir o padrão de dashcase. 
Exemplo: 
getExpensesByExpenseTypeId deverá ser get-expenses-by-expense-type
getDescriptionTypes deverá ser get-description-types

**Comment by fredcido** [comment]
@gilsonterra  @globtec Ainda sobre o DataRepositoryController, não dá para usar o serviço $this->get('serializer') para serializar as entidades? Já é padrão do Symfony, ao invés do método serializeEntityToJson ?

**Comment by adrianorc** [comment]
@fredcido Dá pra usar o $this->get('serializer') sim. Esse método serializeEntityToJson foi eu que criei. É pq o serviço de serializer não estava disponível. Eu instalei e usei conforme a documentação.

http://symfony.com/doc/current/components/serializer.html

Mas dá pra usar o serviço sim. Eu vou alterar lá.

**Comment by fredcido** [comment]
@globtec Algum progresso nisso Zé?

**Comment by fredcido** [comment]
@gilsonterra O Backend ta pronto, preciso do front enviando dados para eu testar, estou com preguiça de montar essa estrutura de dados toda para teste

**Comment by gilsonterra** [comment]
@fredcido eu acho que tem algum problema nos relacionamentos de Intervention Area e Social Response do ISS. Cadastrei um e não estão vindo, olhei no banco de dados e não achei a chave de social response com a intervention area e com a iss.

@fredcido Só pra te lembrar de verificar no backend a questão do excluir!
