### ISSUE TITLE
Verificar tradução de mensagens dos validators nas entities

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#48]

**Comment by adrianorc** [comment]
@fredcido Para traduzir as mensagens dos validators da entity, basca colocar só a chave da mensagem e não a string em si no validator. Veja exemplo:

```
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=200, unique=true)
     * @Assert\NotBlank(message = "not_blank")
     * @Assert\Length(
     *      min = 2,
     *      max = 200,
     *      minMessage = "min_chars",
     *      maxMessage = "max_chars"
     * )     
     */
    private $name;
```

Nesse caso, ao rodar o comando para coletar as strings, vão ser criadas três entradas no dominio validator:
- not_blank
- min_chars
- max_chars

Então, basta acessar a url _trans e traduzir.

Já fiz para a entity InterventionAreas
