### ISSUE TITLE
Verificar uma forma melhor de manipular traduções de termos não usados diretamente no código

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#53]
Como adicionaremos tradução de termos não referenciados explicitamente no código? Adicionar na XML na mão? Usar yml?

**Comment by adrianorc** [comment]
Manipular XML e YML na mão pode ser um pouco chato, não?

Que tal a gente criar uma classe só pra colocar essas mensagens? Algo do tipo:

```
<?php

class Messages {

    const MESSAGE_A = 'message.key.a';
    const MESSAGE_B = 'message.key.b';
    const MESSAGE_C = 'message.key.c';
    const MESSAGE_D = 'message.key.d';

    static $messages = [
        self::MESSAGE_A => $translator->trans(self::MESSAGE_A),
        self::MESSAGE_B => $translator->trans(self::MESSAGE_B),
        self::MESSAGE_C => $translator->trans(self::MESSAGE_C),
        self::MESSAGE_D => $translator->trans(self::MESSAGE_D),
    ] 

    public static function get($key) {
        return self::$messages[$key];
    }

}
```

Pelo menos você deixa uma referência da mensagem no código, e o JMS translator consegue encontrá-la e gerenciar isso no XMl pra gente

O que acha?

**Comment by fredcido** [comment]
@adrianorc Se o JMS conseguir identificar vc usando assim e a gente puder traduzir pelo painel, tudo bem.

**Comment by adrianorc** [comment]
Feito. Já implementei algumas mensagens que estavam fixas no código do form.js.

**Comment by fredcido** [comment]
@gilsonterra @globtec @adrianorc Todas as mensagens usadas em seu código JS (Riot) ou em views que não são identificadas pelo tradutor por padrão, adicionar na classe AppBundle\Message\Message. Para que possam ser traduzidos.

**Comment by fredcido** [comment]
@adrianorc Parece que o comando:

php```
php bin/console translation:extract pt --config=app

```

Sobrescreve as traduções já feitas. Se for assim toda vez que rodar vai bichar as traduções, pode conferir?
```
