### ISSUE TITLE
Criar entity e tela para configurações gerais do sistema

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#55]
Existirão valores que precisarão ser parametrizados, mas não inserido constantemente. Criar uma entity de Settings, seguindo a idéia da tabela wp_options do Wordpress. Por exemplo:

| name | value |
| --- | --- |
| min_cost | 10 |
| max_cost | 100 |
| max_beneficiaries | 500 |

O usuário poderá alterar os valores dessas configurações, mas somente os valores. Criar ENUM para essa configurações e uma forma rápida de recuperar isso. Algo como:

``` php
Settings::get(Settings::MIN_COST);
```

**Comment by adrianorc** [comment]
@fredcido Concluido. Pode ser usado como: 

```
$this->get('app.settings')->get(\AppBundle\Service\Settings::MAX_COST)
```
