### ISSUE TITLE
Adicionar Validators nas Entities

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#56]
Adicionar os validatores de NotBlank e o que mais precisar nas Entities, seguir manual:

https://symfony.com/doc/current/validation.html

Só será necessário adicionar as annotations, o resto é trabalhado pelo form.

**Comment by adrianorc** [comment]
Validadores adicionados

**Comment by fredcido** [comment]
@adrianorc Confere uma questão para mim, parece que os relacionamentos ManyToOne estão aceitando NULL. Teste na Expense por exemplo, se ela está aceitando ExpenseType como NULL, não deveria, mas só para confirmar.

**Comment by adrianorc** [comment]
@fredcido Feito. ExpenseType agora é obrigatório para Expense. 

https://bitbucket.org/fredcido/mss-iss/commits/ddc1c88cdff8819688662c862473c6cfa7157deb

**Comment by adrianorc** [comment]
@fredcido @gilsonterra @globtec Adicionei em quase todos os relacionamentos ManyToOne a obrigatoriedade. Talvez dê problema ao rodar o schema:update por causa de dados inválidos (fk que era null agora deve ter valor).

https://bitbucket.org/fredcido/mss-iss/commits/2d1f1473004c092fba1e98fd995a07b7709d8db5
