### ISSUE TITLE
Criar tela de registro de usuários

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#6]

**Comment by fredcido** [comment]
Colocar um campo de linguagem padrão do usuário. Na hora de cadastrar usuário também pode selecionar a ROLE dele. Desabilitar registro do sistema pela tela do login.

**Comment by adrianorc** [comment]
@fredcido Tá funcionando, mas as roles estão estáticas no código. Eu criei uma tabela de roles: AppBundle:Role. Quanto tiver um tempo dá uma olhada nesse arquivo pra ver onde to errando

```
AppBundle\Form\UserType
```

Eu queria que as roles viessem do banco, mas quando ele vai renderizar os combos na tela, ele não tá marcando quais roles o usuário já possui. Quando as roles estão estáticas, ele marca.

Também intalei o fixtures pra carregar os dados.
