### ISSUE TITLE
Adiconar campo de Status de ISS

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#64]
Falta o campo de status na ISS. Esse campo é diferente das demais entidades no sistema, inclusive já existe entidade criada para tal. Segundo excel, os possiveis valores até então são:

Sem Estatuto de ISS
Estatuto de ISS
Cumpre Normas Técnicas

Colocar no cadastro de ISS, na listagem, no form e salvando no backend. Verificar se já tem relacionamento com a entidade de ISS.

Colocar esses 3 valores no load por enquanto.

**Comment by gilsonterra** [comment]
@fredcido Eu criei la no load, criei no form so que da um erro na hora de inserir no back end. Pode olhar pra mim o que e?

**Comment by fredcido** [comment]
@gilsonterra Testa novamente e corrige a questão dos campos mane e feto
