### ISSUE TITLE
Fazer um NOT FOUND nas rotas

### ISSUE THREAD

**Issue by gilsonterra** [fredcido/mss-iss#68]

**Comment by fredcido** [comment]
@gilsonterra Você quer dizer uma página de 404?

**Comment by gilsonterra** [comment]
@fredcido sim!

**Comment by globtec** [comment]
@gilsonterra @fredcido Foi definido as páginas de erro 404 e 500, para visualizar no ambiente de desenvolvimento use os seguintes endereços:

```
http://127.0.0.1:8000/_error/404
http://127.0.0.1:8000/_error/500
```

@fredcido Aplicar a tradução dos textos das páginas de erro

**Comment by fredcido** [comment]
@globtec Mas não está interceptando as rotas inválidas?

**Comment by globtec** [comment]
@fredcido Sim, aplicado apenas para o ambiente de produção
