### ISSUE TITLE
Implementar tiles semelhantes ao print em anexo

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#69]
Implementar shortcuts na home como os tiles na imagem, levar em consideração acesso, cada ícone é um link para a tela:

![image](https://zube.io/files/fredcido/57b103548437d0c35caf17ec0b58cbbe.png)

**Comment by adrianorc** [comment]
@fredcido Feito. Vai ser mostrado na página inical os 4 itens do menu mais acessados.

Commit:
https://bitbucket.org/fredcido/mss-iss/commits/83b932fe397bc3f759f501b0da74c2081b137904

**Comment by fredcido** [comment]
@adrianorc Uma curiosidade? Como e onde você fez definição das cores e ícones dos tiles? Dá para fazer as cores aleatórias? E os ícones? Como faremos?

**Comment by adrianorc** [comment]
@fredcido Para o ícone, eu criei um método na classe Menu para setar. Por enquanto tá sentando apenas uma classe do font-awesome "$menu->setIcon('fa fa-file')". Dá pra mudar também, pra ser uma imagem no assets, sei la. Dá uma olhada nesse arquivo:

https://bitbucket.org/fredcido/mss-iss/src/2b71ca60740bed0e17d7610c36ec18ced75e992e/src/MenuBundle/MainMenu.php?at=master&fileviewer=file-view-default

Para as cores, por enquanto tá tudo sendo exibido em vermelho. Mas dá pra criar um método também pra setar a cor no menu item, ou gera um cor aleatória para cada item. O que você achar melhor.

**Comment by fredcido** [comment]
@adrianorc Coloca as cores aleatórias. Os icones vamos usar esse font-awesome mesmo. A gente define para as telas.

**Comment by adrianorc** [comment]
@fredcido Feito. Também atualizei os icones de cada tela, de acordo com a uri. Ele busca o item de menu correspondente e seta o ícone no titulo de acordo.
