### ISSUE TITLE
Alterar relacionamento de Expenses

### ISSUE THREAD

**Issue by fredcido** [fredcido/mss-iss#72]
As Expenses não precisam mais de ExpenseType. Elas terão hierarquia recursiva, ou seja, uma pode ser parent da outra, sem limite.
Mudar a entidade e a tela de Expenses, não vamos fazer uma listagem, ao abrir a tela usar uma tree view onde as Expenses podem ser adicionadas e utilizar Drag and Drop para reposicioná-las na árvore.

Lembrando que as Expenses ainda precisam ser vinculadas a uma tabela de Referência (ExpenseReference). Utillizar o seguinte componente já presente no tema: http://keenthemes.com/preview/metronic/theme/admin_1/ui_tree.html

**Comment by adrianorc** [comment]
@fredcido Feito. Foram criados os campos parent e children na entity Expense, para fazer a hierarquia. O campo expenseType foi removido também. A tela de index de expenses também foi alterada para um treeView com drag and drop para alteração dos pais de cada expense.

As expenses ainda continuam sendo vinculadas a tabela de Referencia (ExpenseReferencia)

**Comment by fredcido** [comment]
@adrianorc Vamos lá:
- Não tem como o usuário editar a Expense nessa tela
- Para fazer essa reorganização ele precisa primeiro selecionar a ExpenseReference e então listar as Expenses dela. Cada ExpenseReference por vez
- Como fica mudança de status da Expense? Pode adicionar uma combo no form se for o caso

**Comment by adrianorc** [comment]
@fredcido Testa de novo la. 
- Eu tinha colocado a edição no botão direito do mouse. Mas realmente não tinha ficado intuitivo para o usuário. Tive que criar um plugin para fazer um lápis aparecer na árvore.
- Também coloquei um campo para filtrar as References na tela.
- Pra fazer a alteração de status, eu inclui o plugin de checkbox. O usuário seleciona na árvore os itens para trocar o status, e vai do menu de trocar de status e seleciona ativo ou inativo.

**Comment by fredcido** [comment]
@adrianorc  Ficou bom, unico problema é que a checkbox marca parents e filhos, tem como marcar só aquela leaf? Retira o botão Search e faz listar ao mudar a ExpenseReference e mostrar sempre todos, ativos e inativos, se tiver como mostrar um inativo com uma folha vermelha, não sei.

**Comment by adrianorc** [comment]
@fredcido Pronto. Fiz estas alterações aí. Testa lá depois.

**Comment by fredcido** [comment]
@adrianorc Perfeito
